### PR TITLE
Create brochures_UsersStories

### PR DESCRIPTION
**Pull request by mhabimana**
Folder to keep brochures and users stories

### CODE REVIEW

**Comment by mhabimana** [comment]
@isedwards -I think this one is ok now

**Comment by mhabimana** [comment]
@isedwards- Thanks.

**Comment by isedwards** [comment]
This has created a folder called `ClimsoftBrochures_UsersStories` that contains an empty file called `brochures_UsersStories`.

I'm happy reviewing and merging, but let me know if you'd prefer to have write access to the repository.

**Comment by mhabimana** [comment]
> This has created a folder called `ClimsoftBrochures_UsersStories` that contains an empty file called `brochures_UsersStories`.
> 
> I'm happy reviewing and merging, but let me know if you'd prefer to have write access to the repository.

@isedwards -I wanted to add a folder only where I will be uploading Climsoft brochures and user stories .

**Comment by mhabimana** [comment]
@isedwards- I can see I don't have access yet to this folder, pls grant me access.

**Comment by isedwards** [comment]
I've given you write access - let me know if you have any problems

**Comment by mhabimana** [comment]
@isedwards - Cool,thanks.

**Pull request merged**
